name: Deploy Prestige Hostel

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deployment Pipeline
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: "npm"

      - name: Route to backend folder
        run: cd backend

      - name: Install backend dependencies
        run: npm ci --legacy-peer-deps

      - name: Run unit tests
        run: npm test -- --ci
