name: store-api

on:
  push:
    branches:
      - master

jobs:
  build_and_push_images:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code.
        uses: actions/checkout@v3

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push backend image.
        run: |
          cd backend
          docker build -t allanbinga/backendstoreapi:v1.0.0 .
          docker push allanbinga/backendstoreapi:v1.0.0
 #image 1
      - name: Build and push client image.
        run: |
          cd client
          docker build -t allanbinga/clientstoreapi:v1.0.0 .
          docker push allanbinga/clientstoreapi:v1.0.0

      #image 2
      - name: Build and push client2 image. 
        run: |
          cd client2
          docker build -t allanbinga/client2storeapi:v1.0.0 .
          docker push allanbinga/client2storeapi:v1.0.0

